adb shell pm disable-user --user 0 se.dirac.acs
adb shell pm disable-user --user 0 com.xiaomi.xmsf
adb shell pm disable-user --user 0 com.xiaomi.upnp
adb shell pm disable-user --user 0 com.xiaomi.simactivate.service
adb shell pm disable-user --user 0 com.xiaomi.scanner
adb shell pm disable-user --user 0 com.xiaomi.payment
adb shell pm disable-user --user 0 com.xiaomi.mirecycle
adb shell pm disable-user --user 0 com.xiaomi.mipicks
adb shell pm disable-user --user 0 com.xiaomi.midrop
adb shell pm disable-user --user 0 com.xiaomi.micloud.sdk
adb shell pm disable-user --user 0 com.xiaomi.mi_connect_service
adb shell pm disable-user --user 0 com.xiaomi.location.fused
adb shell pm disable-user --user 0 com.xiaomi.joyose
adb shell pm disable-user --user 0 com.xiaomi.glgm
adb shell pm disable-user --user 0 com.xiaomi.discover
adb shell pm disable-user --user 0 com.xiaomi.bluetooth
adb shell pm disable-user --user 0 com.wapi.wapicertmanage
adb shell pm disable-user --user 0 com.quicinc.cne.CNEService
adb shell pm disable-user --user 0 com.qualcomm.wfd.service
adb shell pm disable-user --user 0 com.qualcomm.uimremoteclient
adb shell pm disable-user --user 0 com.qualcomm.qti.uceShimService
adb shell pm disable-user --user 0 com.qualcomm.qti.qmmi
adb shell pm disable-user --user 0 com.qualcomm.qti.qcom_accesslogkit
adb shell pm disable-user --user 0 com.qualcomm.qti.auth.securesampleauthservice
adb shell pm disable-user --user 0 com.qualcomm.qti.auth.fidocryptoservice
adb shell pm disable-user --user 0 com.qualcomm.qti.accesscache
adb shell pm disable-user --user 0 com.qti.xdivert
adb shell pm disable-user --user 0 com.qti.service.colorservice
adb shell pm disable-user --user 0 com.qapp.secprotect
adb shell pm disable-user --user 0 com.miui.yellowpage
adb shell pm disable-user --user 0 com.miui.wmsvc
adb shell pm disable-user --user 0 com.miui.weather2
adb shell pm disable-user --user 0 com.miui.vsimcore
adb shell pm disable-user --user 0 com.miui.videoplayer
adb shell pm disable-user --user 0 com.miui.translationservice
adb shell pm disable-user --user 0 com.miui.translation.youdao
adb shell pm disable-user --user 0 com.miui.translation.xmcloud
adb shell pm disable-user --user 0 com.miui.translation.kingsoft
adb shell pm disable-user --user 0 com.miui.touchassistant
adb shell pm disable-user --user 0 com.miui.smsextra
adb shell pm disable-user --user 0 com.miui.screenrecorder
adb shell pm disable-user --user 0 com.miui.providers.weather
adb shell pm disable-user --user 0 com.miui.player
adb shell pm disable-user --user 0 com.miui.notes
adb shell pm disable-user --user 0 com.miui.msa.global
adb shell pm disable-user --user 0 com.miui.miwallpaper
adb shell pm disable-user --user 0 com.miui.miservice
adb shell pm disable-user --user 0 com.miui.micloudsync
adb shell pm disable-user --user 0 com.miui.hybrid.accessory
adb shell pm disable-user --user 0 com.miui.hybrid
adb shell pm disable-user --user 0 com.miui.freeform
adb shell pm disable-user --user 0 com.miui.fm
adb shell pm disable-user --user 0 com.miui.face
adb shell pm disable-user --user 0 com.miui.daemon
adb shell pm disable-user --user 0 com.miui.core
adb shell pm disable-user --user 0 com.miui.compass
adb shell pm disable-user --user 0 com.miui.cloudservice.sysbase
adb shell pm disable-user --user 0 com.miui.cloudservice
adb shell pm disable-user --user 0 com.miui.cloudbackup
adb shell pm disable-user --user 0 com.miui.cleanmaster
adb shell pm disable-user --user 0 com.miui.calculator
adb shell pm disable-user --user 0 com.miui.bugreport
adb shell pm disable-user --user 0 com.miui.backup
adb shell pm disable-user --user 0 com.miui.audioeffect
adb shell pm disable-user --user 0 com.miui.antispam
adb shell pm disable-user --user 0 com.miui.android.fashiongallery
adb shell pm disable-user --user 0 com.miui.analytics
adb shell pm disable-user --user 0 com.mipay.wallet.in
adb shell pm disable-user --user 0 com.mipay.wallet.id
adb shell pm disable-user --user 0 com.milink.service
adb shell pm disable-user --user 0 com.micredit.in
adb shell pm disable-user --user 0 com.mi.webkit.core
adb shell pm disable-user --user 0 com.mi.globalTrendNews
adb shell pm disable-user --user 0 com.mi.android.globalpersonalassistant
adb shell pm disable-user --user 0 com.mi.android.globalFileexplorer
adb shell pm disable-user --user 0 com.mi.AutoTest
adb shell pm disable-user --user 0 com.mfashiongallery.emag
adb shell pm disable-user --user 0 com.huaqin.sar
adb shell pm disable-user --user 0 com.huaqin.factory
adb shell pm disable-user --user 0 com.huaqin.diaglogger
adb shell pm disable-user --user 0 com.google.android.youtube
adb shell pm disable-user --user 0 com.google.android.videos
adb shell pm disable-user --user 0 com.google.android.tts
adb shell pm disable-user --user 0 com.google.android.syncadapters.contacts
adb shell pm disable-user --user 0 com.google.android.syncadapters.calendar
adb shell pm disable-user --user 0 com.google.android.setupwizard
adb shell pm disable-user --user 0 com.google.android.printservice.recommendation
adb shell pm disable-user --user 0 com.google.android.partnersetup
adb shell pm disable-user --user 0 com.google.android.onetimeinitializer
adb shell pm disable-user --user 0 com.google.android.music
adb shell pm disable-user --user 0 com.google.android.marvin.talkback
adb shell pm disable-user --user 0 com.google.android.inputmethod.latin
adb shell pm disable-user --user 0 com.google.android.gsf
adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox
adb shell pm disable-user --user 0 com.google.android.gms
adb shell pm disable-user --user 0 com.google.android.gm
adb shell pm disable-user --user 0 com.google.android.feedback
adb shell pm disable-user --user 0 com.google.android.backuptransport
adb shell pm disable-user --user 0 com.google.android.apps.tachyon
adb shell pm disable-user --user 0 com.google.android.apps.photos
adb shell pm disable-user --user 0 com.google.android.apps.maps
adb shell pm disable-user --user 0 com.google.android.apps.docs
adb shell pm disable-user --user 0 com.goodix.gftest
adb shell pm disable-user --user 0 com.goodix.fingerprint
adb shell pm disable-user --user 0 com.fingerprints.sensortesttool
adb shell pm disable-user --user 0 com.fingerprints.extension.service
adb shell pm disable-user --user 0 com.fido.xiaomi.uafclient
adb shell pm disable-user --user 0 com.fido.asm
adb shell pm disable-user --user 0 com.facebook.system
adb shell pm disable-user --user 0 com.facebook.services
adb shell pm disable-user --user 0 com.facebook.appmanager
adb shell pm disable-user --user 0 com.dsi.ant.server
adb shell pm disable-user --user 0 com.android.wallpapercropper
adb shell pm disable-user --user 0 com.android.wallpaperbackup
adb shell pm disable-user --user 0 com.android.wallpaper.livepicker
adb shell pm disable-user --user 0 com.android.vending
adb shell pm disable-user --user 0 com.android.thememanager.module
adb shell pm disable-user --user 0 com.android.thememanager
adb shell pm disable-user --user 0 com.android.storagemanager
adb shell pm disable-user --user 0 com.android.statementservice
adb shell pm disable-user --user 0 com.android.soundrecorder
adb shell pm disable-user --user 0 com.android.sharedstoragebackup
adb shell pm disable-user --user 0 com.android.providers.userdictionary
adb shell pm disable-user --user 0 com.android.providers.partnerbookmarks
adb shell pm disable-user --user 0 com.android.providers.calendar
adb shell pm disable-user --user 0 com.android.providers.blockednumber
adb shell pm disable-user --user 0 com.android.printspooler
adb shell pm disable-user --user 0 com.android.pacprocessor
adb shell pm disable-user --user 0 com.android.managedprovisioning
adb shell pm disable-user --user 0 com.android.keychain
adb shell pm disable-user --user 0 com.android.fileexplorer
adb shell pm disable-user --user 0 com.android.emergency
adb shell pm disable-user --user 0 com.android.egg
adb shell pm disable-user --user 0 com.android.dreams.phototable
adb shell pm disable-user --user 0 com.android.dreams.basic
adb shell pm disable-user --user 0 com.android.deskclock
adb shell pm disable-user --user 0 com.android.cts.priv.ctsshim
adb shell pm disable-user --user 0 com.android.cts.ctsshim
adb shell pm disable-user --user 0 com.android.companiondevicemanager
adb shell pm disable-user --user 0 com.android.chrome
adb shell pm disable-user --user 0 com.android.camera
adb shell pm disable-user --user 0 com.android.calllogbackup
adb shell pm disable-user --user 0 com.android.calendar
adb shell pm disable-user --user 0 com.android.browser
adb shell pm disable-user --user 0 com.android.bookmarkprovider
adb shell pm disable-user --user 0 com.android.bips
adb shell pm disable-user --user 0 com.android.backupconfirm
adb shell pm disable-user --user 0 cn.wps.xiaomi.abroad.lite
